### ISSUE TITLE
有个问题请教一下

### ISSUE THREAD

**Issue by wangshaolei** [BCsl/GalleryLayoutManager#1]
实际运用中有个问题，我现在用的是
GalleryLayoutManager.HORIZONTAL
galleryLayoutManager.setItemTransformer(new ScaleTransformer());
GalleryAdapter galleryAdapter = new GalleryAdapter(thumbs);
thumbs10张
但是刚进页面时，大概有7，8次滑动bug，只要滑到第4张就自动跳到第1张。 这个情况bug，能持续7，8个回合，然后滑动到最后一张就又正常了。

**Comment by BCsl** [comment]
@wangshaolei 可以发个 DEMO 来看看嘛？或是给个 git 也可以，而且确保引用版本是 1.0.3

**Comment by wangshaolei** [comment]
@BCsl 我是直接下的源码，直接copy过去源码的

**Comment by BCsl** [comment]
源码也确保是当前最新的？

**Comment by wangshaolei** [comment]
@BCsl 
是的我刚下的，发现有问题才想问你一下，时间来不及，没去追究问题所在。希望见谅。
还有一个问题是 我当前选中在第5张，我只要edittext获取键盘就自动跳到第一张。
稍等我可以录个视频给你看看？抽demo的话，东西有点多。

**Comment by BCsl** [comment]
@wangshaolei 单纯看视频比较难看出问题，尽量给个 DEMO 看看你怎么使用

**Comment by wangshaolei** [comment]
@BCsl 好的，我空下来， 给你发个demo源码

**Comment by wangshaolei** [comment]
@BCsl 我直接发你qq邮箱。

**Comment by wangshaolei** [comment]
@BCsl hi, already send your email

**Comment by BCsl** [comment]
@wangshaolei 已解决

**Comment by wangshaolei** [comment]
@BCsl 收到。抽时间我跟下源码实现 方式。
