### ISSUE TITLE
Select Position in RecyclerView

### ISSUE THREAD

**Issue by bnottingham** [BCsl/GalleryLayoutManager#10]
As far as I can tell you can not programmatically select a position in the recycler view.  I tried smoothscroll, scrollby, scrollto, etc and there is no effect.

Is there any way to select a position in the recyclerview and have it scroll to that position?

**Comment by MuhamedFathy** [comment]
I know this is too late but you can use `recyclerView.smoothScrollToPosition()` inside `post()` block like this:

`recyclerView.post { recyclerView.smoothScrollToPosition(position) }`
