### ISSUE TITLE
RecyclerView in MaterialDialogs library

### ISSUE THREAD

**Issue by OlegRy** [BCsl/GalleryLayoutManager#2]
I tried use your library in Activity and it works fine. But when I try use your library with afollestad MaterialDialogs library, all I have is empty dialog. There's a source:
`      MaterialDialog.Builder builder = new MaterialDialog.Builder(this);
        builder.title("Выберите год");
        View customView = LayoutInflater.from(this).inflate(R.layout.picker_view, null);
        RecyclerView recyclerView = (RecyclerView) customView.findViewById(com.allgoritm.youla.R.id.years);

        GalleryLayoutManager manager = new GalleryLayoutManager(GalleryLayoutManager.VERTICAL);
        manager.setCallbackInFling(true);
        manager.setOnItemSelectedListener((recyclerView1, item, position) -> {
            Log.d(TestActivity.class.getSimpleName(), "AHAHAHAHA");
        });
        manager.attach(recyclerView, 40);
        mAdapter = new PickerAdapter(getYears());
        mAdapter.setCallback(this);
        recyclerView.setAdapter(mAdapter);

        builder.customView(customView, true);
        builder.positiveText("Ок");
        builder.onPositive(new MaterialDialog.SingleButtonCallback() {
            @Override
            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                Log.d(TestActivity.class.getSimpleName(), "cool");
            }
        });

        builder.show();`
Is your library supports working with dialogs?

**Comment by BCsl** [comment]
What 's the problem with it ?  I think it would work well If LinearLayoutManager or any other build-in LayoutManager work well

**Comment by OlegRy** [comment]
@BCsl Problem was solved: I've made custom view with fixed size and it works
