### ISSUE TITLE
点击删除条目bug

### ISSUE THREAD

**Issue by ZhangQixiangChina** [BCsl/GalleryLayoutManager#4]
我加了点击删除条目的功能,
在定位到position=1的条目后点击删除这个条目(调用notifyitemremoved), 然后position为0的条目也会跟着不见了,定位到其他position上没这个问题

**Comment by ZhangQixiangChina** [comment]
我解决了, 

在fillLeft方法中的for循环:
for (int i = startPosition; i > 0 && startOffset > leftEdge; i--) 

改成:
for (int i = startPosition; **i >= 0** && startOffset > leftEdge; i--) {

**Comment by BCsl** [comment]
@ZhangQixiangChina  谢谢，我会验证下

**Comment by BCsl** [comment]
@ZhangQixiangChina 我自己试了下，并没出现你的问题，但后续有出现其他问题，因为库没有考虑 ```onItemsRemoved``` 这类方法，但 for 循环的逻辑上应该是没错

**Comment by ZhangQixiangChina** [comment]
是这样的,删除item后会重新定位到最开始设置的selectPosition上, 所以我每次删除的时候都先把那个mInitialSelectedPosition(我加了set方法),重新设置一下:

 ```
private void setNewSelectPos(int position) {
            boolean isClickLast = position == mAdapter.getItemCount() - 1;
            if (isClickLast) {
                //mLm -->GalleryLayoutManager
                mLm.setSelectPosition(position - 1);

            } else {
                mLm.setSelectPosition(position);

            }
        }
```
然后因为fillLeft中(fillTop也是一样) startPosition取值是mInitialSelectedPosition-1, 那么当我删除第2个(position为1的)条目时,startPosition就是0,然后for里面就不会走,导致position为0的那个条目不显示.

另外notifyItemRemove时系统默认动画会把有些条目的translation重新变为0, transformer里设置translation属性不起作用, 后来我改了DefaultItemAnimator解决的 (oﾟ▽ﾟ)o

**Comment by BCsl** [comment]
还真有问题，谢谢
