### ISSUE TITLE
无法使用scrollToPosition会有大问题

### ISSUE THREAD

**Issue by Pannarrow** [BCsl/GalleryLayoutManager#41]
smoothScrollToPosition可以使用，scrollToPosition无法使用，导致切换视图时无法定位到指定position，切换完成后出现一个平滑滚动的动画效果

**Comment by BudingShuo** [comment]
这个如何解决

**Comment by Pannarrow** [comment]
So what I do is I reset setLayoutManager(null) and setOnFlingListener(null) and then I call attach() again
