### ISSUE TITLE
scrollToPosition(int position) not working

### ISSUE THREAD

**Issue by genaku** [BCsl/GalleryLayoutManager#7]
Thank you for nice library! Would you like to add implementation of scrollToPosition(int position)? It will be great as there is need to start show gallery from specified position.

**Comment by BCsl** [comment]
How about use `smoothScrollToPosition` ?

**Comment by BCsl** [comment]
You can use  `GalleryLayoutManager#attach(RecycleView view, int position)`  to specify the initial position
